// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///

class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA8MuAkwKVsFhQIx4PLXJ3hGeouo8sU18k',
    appId: '1:937366143290:web:5f8b67324629e2b72f1003',
    messagingSenderId: '937366143290',
    projectId: 'fluttercontact-4abb1',
    authDomain: 'fluttercontact-4abb1.firebaseapp.com',
    storageBucket: 'fluttercontact-4abb1.appspot.com',
    measurementId: 'G-LDN6WQC1ZT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYV2myhasxA53FrRtqMAKbEJMF9s4G26I',
    appId: '1:937366143290:android:9481140ba966b0422f1003',
    messagingSenderId: '937366143290',
    projectId: 'fluttercontact-4abb1',
    storageBucket: 'fluttercontact-4abb1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA18VoTTxo-aQpQY1XneNcbWGepYYfqhkI',
    appId: '1:937366143290:ios:75c7d11aca1599fc2f1003',
    messagingSenderId: '937366143290',
    projectId: 'fluttercontact-4abb1',
    storageBucket: 'fluttercontact-4abb1.appspot.com',
    iosBundleId: 'com.example.flutterFirebaseContact',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA8MuAkwKVsFhQIx4PLXJ3hGeouo8sU18k',
    appId: '1:937366143290:web:569e91297726b5252f1003',
    messagingSenderId: '937366143290',
    projectId: 'fluttercontact-4abb1',
    authDomain: 'fluttercontact-4abb1.firebaseapp.com',
    storageBucket: 'fluttercontact-4abb1.appspot.com',
    measurementId: 'G-13H31GLG4P',
  );

}
